# Generated by Django 4.1.2 on 2022-11-03 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='lyrics',
            new_name='Lyric',
        ),
    ]
